"""
nexus-time-series-forecast-api — CrewAI Tool Wrappers
Generated by NEXUS v6.0. Talks real MCP protocol via _mcp_client.py.

Usage:
    from sdk_wrappers.crewai_tool import CalibrateBassDiffusionMleTool

    @agent
    class MyAgent(Agent):
        tools = [CalibrateBassDiffusionMleTool()]
"""

from typing import Any
from crewai_tools import BaseTool
from pydantic import BaseModel, Field

from ._mcp_client import call_mcp_tool

class CalibrateBassDiffusionMleInput(BaseModel):
    adoption_series: list[float] = Field(..., description='Historical cumulative or periodic adoption numbers (e.g., cumulative users per day). Must be non-negative and increasing or non-decreasing.')
    market_potential_prior: float = Field(..., description='Prior estimate of total addressable market size (M). Must be greater than the last value of adoption_series.')
    mle_max_iterations: float = Field(..., description='Maximum number of iterations for the MLE optimization algorithm.')


class CalibrateBassDiffusionMleTool(BaseTool):
    name: str = "nexus_time_series_forecast_api_calibrate_bass_diffusion_mle"
    description: str = 'Calibrates Bass diffusion model parameters (p_innovation, q_imitation, M_market_potential) via Maximum Likelihood Estimation on the provided historical adoption series. Use to estimate model coefficients from observed adoption data, especially with at least 15 points. Do NOT use for very short series (<5 points) or when adoption is still in the initial flat phase without a clear inflection – the MLE may fail to converge.'
    args_schema: type[BaseModel] = CalibrateBassDiffusionMleInput

    def _run(self, adoption_series, market_potential_prior, mle_max_iterations) -> Any:
        return call_mcp_tool("nexus_time_series_forecast_api_calibrate_bass_diffusion_mle", {"adoption_series": adoption_series, "market_potential_prior": market_potential_prior, "mle_max_iterations": mle_max_iterations})

class ForecastBassAdoptionCurveInput(BaseModel):
    adoption_series: list[float] = Field(..., description='Historical adoption series used for optional entropy computation and as a baseline for forecast alignment.')
    horizon_steps: float = Field(..., description='Number of future steps to forecast. Must be a positive integer.')
    p_innovation: float = Field(..., description='Coefficient of innovation (p) from Bass calibration.')
    q_imitation: float = Field(..., description='Coefficient of imitation (q) from Bass calibration.')
    M_market_potential: float = Field(..., description='Estimated total market potential (saturation level). Must be > 0.')
    entropy_cutoff_threshold: float = Field(..., description='Marginal entropy gain threshold per step (in bits) below which the forecast horizon is cut off.')


class ForecastBassAdoptionCurveTool(BaseTool):
    name: str = "nexus_time_series_forecast_api_forecast_bass_adoption_curve"
    description: str = 'Generates future adoption values over a given horizon using the Bass diffusion model. The forecast is truncated if the conditional entropy exceeds the configured threshold, ensuring only reliable steps are returned. Use when you have calibrated Bass parameters and need a numeric forecast with an entropy-based reliability cutoff. Do NOT use without first providing valid p, q, M parameters (missing parameters will raise BassParamsMissingError).'
    args_schema: type[BaseModel] = ForecastBassAdoptionCurveInput

    def _run(self, adoption_series, horizon_steps, p_innovation, q_imitation, M_market_potential, entropy_cutoff_threshold) -> Any:
        return call_mcp_tool("nexus_time_series_forecast_api_forecast_bass_adoption_curve", {"adoption_series": adoption_series, "horizon_steps": horizon_steps, "p_innovation": p_innovation, "q_imitation": q_imitation, "M_market_potential": M_market_potential, "entropy_cutoff_threshold": entropy_cutoff_threshold})

class ComputeEntropyDegradationProfileInput(BaseModel):
    adoption_series: list[float] = Field(..., description='Historical adoption series for estimating the state distribution.')
    horizon_steps: float = Field(..., description='Number of future steps for which to compute entropy.')
    n_bins: float = Field(..., description='Number of bins for discretizing continuous values to estimate empirical entropy. Must be at least 2.')
    p_innovation: float = Field(..., description='Coefficient of innovation (p).')
    q_imitation: float = Field(..., description='Coefficient of imitation (q).')
    M_market_potential: float = Field(..., description='Estimated market potential.')


class ComputeEntropyDegradationProfileTool(BaseTool):
    name: str = "nexus_time_series_forecast_api_compute_entropy_degradation_profile"
    description: str = 'Computes the Shannon conditional entropy H(X_{t+k}|X_{1..t}) for each step in the forecast horizon, given the Bass parameters. Provides a trajectory of information degradation. Use to diagnose where the forecast becomes unreliable. Do NOT use if the adoption series has fewer than 10 points, as the conditional entropy estimation requires sufficient historical variability.'
    args_schema: type[BaseModel] = ComputeEntropyDegradationProfileInput

    def _run(self, adoption_series, horizon_steps, n_bins, p_innovation, q_imitation, M_market_potential) -> Any:
        return call_mcp_tool("nexus_time_series_forecast_api_compute_entropy_degradation_profile", {"adoption_series": adoption_series, "horizon_steps": horizon_steps, "n_bins": n_bins, "p_innovation": p_innovation, "q_imitation": q_imitation, "M_market_potential": M_market_potential})

class ResolveForecastHorizonByEntropyInput(BaseModel):
    entropy_per_step: list[float] = Field(..., description='Array of conditional entropy values per horizon step (starting from step 1).')
    marginal_entropy_threshold: float = Field(..., description='Minimum acceptable increase in entropy per step (bits). Drop below this signals unreliable forecast.')
    absolute_entropy_ceiling: float = Field(..., description='Absolute entropy value (bits) beyond which the forecast is considered too uncertain.')


class ResolveForecastHorizonByEntropyTool(BaseTool):
    name: str = "nexus_time_series_forecast_api_resolve_forecast_horizon_by_entropy"
    description: str = 'Determines the recommended forecast cutoff step from an entropy profile, given thresholds for marginal entropy gain and absolute entropy ceiling. Use after computing the entropy profile to automatically truncate the forecast at the point where information becomes unreliable. Do NOT use if the entropy profile is empty or contains invalid values (e.g., negative or non-monotonic).'
    args_schema: type[BaseModel] = ResolveForecastHorizonByEntropyInput

    def _run(self, entropy_per_step, marginal_entropy_threshold, absolute_entropy_ceiling) -> Any:
        return call_mcp_tool("nexus_time_series_forecast_api_resolve_forecast_horizon_by_entropy", {"entropy_per_step": entropy_per_step, "marginal_entropy_threshold": marginal_entropy_threshold, "absolute_entropy_ceiling": absolute_entropy_ceiling})

class ForecastWithReliabilityMapInput(BaseModel):
    adoption_series: list[float] = Field(..., description='Historical adoption series (cumulative numbers).')
    horizon_steps: float = Field(..., description='Desired forecast horizon (number of steps).')
    market_potential_prior: float = Field(..., description='Prior estimate of the market potential M for Bass calibration.')
    marginal_entropy_threshold: float = Field(..., description='Entropy threshold for cutoff (bits).')
    n_bins: float = Field(..., description='Number of bins for entropy discretization.')
    mle_max_iterations: float = Field(..., description='Maximum iterations for the MLE optimizer.')


class ForecastWithReliabilityMapTool(BaseTool):
    name: str = "nexus_time_series_forecast_api_forecast_with_reliability_map"
    description: str = 'End-to-end pipeline: fits Bass diffusion parameters via MLE, computes conditional entropy profile, resolves cutoff horizon, and returns the forecast along with per-step entropy, marginal gains, and a reliability map. Use as a one-call solution to obtain a complete, entropy-aware forecast. Do NOT use if the input series is too short to calibrate (<15 points) or if market_potential_prior is not a plausible upper bound.'
    args_schema: type[BaseModel] = ForecastWithReliabilityMapInput

    def _run(self, adoption_series, horizon_steps, market_potential_prior, marginal_entropy_threshold, n_bins, mle_max_iterations) -> Any:
        return call_mcp_tool("nexus_time_series_forecast_api_forecast_with_reliability_map", {"adoption_series": adoption_series, "horizon_steps": horizon_steps, "market_potential_prior": market_potential_prior, "marginal_entropy_threshold": marginal_entropy_threshold, "n_bins": n_bins, "mle_max_iterations": mle_max_iterations})